platform :ios, "9.0"
use_frameworks!

target 'Anatomy Lab' do

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'IQKeyboardManagerSwift'
pod 'RealmSwift'
pod 'PopupDialog', '~> 0.3'
pod 'FontAwesome.swift'
pod 'Google/SignIn'
pod 'GoogleAPIClient/Drive', '~> 1.0.2'
pod 'GTMOAuth2', '~> 1.1.0'

end
